package model;

import java.util.ArrayList;
import java.util.Random;

/**
 * Description: The MatrixHandler class provides utility methods to generate and
 * manipulate
 * matrices, as well as generate unique IDs based on rarity.
 */
public class MatrixHandler {

    /**
     * Description: Default constructor for the MatrixHandler class.
     * Initializes an instance of MatrixHandler without any specific setup.
     */
    public MatrixHandler() {

    }

    /**
     * Description: Generates a 4x4 matrix filled with random integers (as Strings)
     * between 0 and 9.
     * 
     * @return A 4x4 String matrix filled with random integers.
     */
    public String[][] generateMatrix() {

        String[][] matrix = new String[4][4];

        Random randomGenerator = new Random();

        for (int i = 0; i < matrix.length; i++) {
            for (int j = 0; j < matrix[0].length; j++) {
                matrix[i][j] = randomGenerator.nextInt(10) + "";
            }
        }

        return matrix;

    }

    /**
     * Description: Generates a unique ID based on the rarity of a Pokémon card.
     * The ID generation process may involve the use of a matrix generated by the
     * generateMatrix method.
     * 
     * Precondition: The rarity parameter must not be null.
     * 
     * @param rarity The rarity of the Pokémon card (e.g., COMMON, RARE, etc.).
     * @return A unique ID as a String based on the rarity.
     */
    public String generateID(Rarity rarity) {

        String id = null;

        String[][] matrix = generateMatrix();

        // Just for quick testing
        // System.out.println(matrixToString(matrix));

        switch (rarity) {
            case NORMAL:
                id = traverseMatrixN(matrix);
                break;
            case RARE:
                id = traverseMatrixZ(matrix);
                break;
            case EPIC:
                id = traverseMatrixX(matrix);
                break;
            case LEGENDARY:
                id = traverseMatrixO(matrix);
                break;
        }
        // Just for quick testing
        // System.out.println(id);

        return id;

    }

    /**
     * Description: Traverses a matrix in a "N" shape starting from the bottom-left
     * cell.
     * 
     * @param matrix The 2D String matrix to traverse.
     * @return A String containing the values of the matrix in "N" traversal order.
     */
    public String traverseMatrixN(String[][] matrix) {
        if (matrix == null || matrix.length == 0 || matrix[0].length == 0) {
            return "Matrix is empty or null.";
        }

        StringBuilder result = new StringBuilder();
        int rows = matrix.length;
        int cols = matrix[0].length;

        // Step 1: Traverse the first column from bottom to top
        for (int i = rows - 1; i >= 0; i--) {
            result.append(matrix[i][0]);
        }

        // Step 2: Traverse diagonally from top-left to bottom-right
        int row = 1, col = 1; // Start from the second column in the top row
        while (row < rows && col < cols) {
            result.append(matrix[row][col]);
            row++;
            col++;
        }

        // Step 3: Traverse the last column from bottom to top
        for (int i = rows - 2; i >= 0; i--) {
            result.append(matrix[i][cols - 1]);
        }

        return result.toString().trim();
    }

    /**
     * Description: Traverses a matrix in a "Z" shape starting from the top-left
     * cell.
     * 
     * @param matrix The 2D String matrix to traverse.
     * @return A String containing the values of the matrix in "Z" traversal order.
     */
    public String traverseMatrixZ(String[][] matrix) {
        if (matrix == null || matrix.length == 0 || matrix[0].length == 0) {
            return "Matrix is empty or null.";
        }

        StringBuilder result = new StringBuilder();
        int rows = matrix.length;
        int cols = matrix[0].length;

        // Step 1: Traverse the first row from left to right
        for (int i = 0; i < cols; i++) {
            result.append(matrix[0][i]);
        }

        // Step 2: Traverse diagonally from top-right to bottom-left
        int row = 1, col = cols - 2; // Start from the second row, second-to-last column
        while (row < rows && col >= 0) {
            result.append(matrix[row][col]);
            row++;
            col--;
        }

        // Step 3: Traverse the last row from left to right
        if (rows > 1) { // Only traverse if there is more than one row
            for (int i = 1; i < cols; i++) {
                result.append(matrix[rows - 1][i]);
            }
        }

        return result.toString().trim();
    }

    /**
     * Description: Traverses a matrix in an "X" shape starting from the top-left
     * cell.
     * 
     * @param matrix The 2D String matrix to traverse.
     * @return A String containing the values of the matrix in "X" traversal order.
     */
    public String traverseMatrixX(String[][] matrix) {
        if (matrix == null || matrix.length == 0 || matrix[0].length == 0) {
            return "Matrix is empty or null.";
        }

        StringBuilder result = new StringBuilder();
        int rows = matrix.length;
        int cols = matrix[0].length;

        // Step 1: Traverse the main diagonal (top-left to bottom-right)
        for (int i = 0; i < Math.min(rows, cols); i++) {
            result.append(matrix[i][i]);
        }

        // Step 2: Traverse the anti-diagonal (top-right to bottom-left)
        for (int i = 0; i < Math.min(rows, cols); i++) {
            // Avoid duplicating the center element in case of a square matrix with odd
            // dimensions
            if (i != rows - i - 1) {
                result.append(matrix[i][cols - i - 1]);
            }
        }

        return result.toString().trim();
    }

    /**
     * Description: Traverses a matrix in an "O" shape starting from the
     * bottom-right cell.
     * 
     * @param matrix The 2D String matrix to traverse.
     * @return A String containing the values of the matrix in "O" traversal order.
     */
    public String traverseMatrixO(String[][] matrix) {
        if (matrix == null || matrix.length == 0 || matrix[0].length == 0) {
            return "Matrix is empty or null.";
        }

        StringBuilder result = new StringBuilder();
        int rows = matrix.length;
        int cols = matrix[0].length;

        // Step 1: Traverse the bottom row from right to left
        for (int i = cols - 1; i >= 0; i--) {
            result.append(matrix[rows - 1][i]);
        }

        // Step 2: Traverse the left column from bottom to top
        for (int i = rows - 2; i >= 0; i--) {
            result.append(matrix[i][0]);
        }

        // Step 3: Traverse the top row from left to right
        if (rows > 1) { // Only traverse if there is more than one row
            for (int i = 1; i < cols; i++) {
                result.append(matrix[0][i]);
            }
        }

        // Step 4: Traverse the right column from top to bottom
        if (cols > 1) { // Only traverse if there is more than one column
            for (int i = 1; i < rows - 1; i++) {
                result.append(matrix[i][cols - 1]);
            }
        }

        return result.toString().trim();
    }

    /**
     * Description: Calculates the number of unique Pokémon types in the Pokedex.
     * 
     * @return The number of unique Pokémon types.
     */

    public int calculateUniquePokemonTypes() {

        return Type.values().length;
    }

    /**
     * Description: Calculates the number of unique Pokémon rarities in the Pokedex.
     * 
     * @return The number of unique Pokémon types.
     */

    public int calculateUniquePokemonRarities() {

        return Rarity.values().length;
    }

    /**
     * Description: Calculates the Pokémon type with the most cards registered in
     * the Pokedex.
     * 
     * Precondition: The pokedex ArrayList must be initialized and may contain Card
     * objects.
     * @param pokedex Arraylist with Cards
     * @return The type with the most cards, or 0 if the Pokedex is empty.
     */
    public int countMostFrequentType(ArrayList<Card> pokedex) {

        if (pokedex.isEmpty()) {
            return 0;
        }

        Type[] types = Type.values();
        int[] counts = new int[Type.values().length];

        for (int i = 0; i < pokedex.size(); i++) {
            for (int j = 0; j < types.length; j++) {
                if (pokedex.get(i).getType() == types[j]) {
                    counts[j]++;
                }
            }

        }

        int maxCount = 0;

        for (int i : counts) {

            if (i > maxCount) {
                maxCount = i;
            }

        }

        return maxCount;

    }

    /**
     * Description: Calculates the count of cards by the type and rarity given.
     * 
     * Precondition: The pokedex ArrayList must be initialized and may contain Card
     * objects.
     * 
     * @param type   type given
     * @param rarity rarity given
     * @param pokedex Arraylist with Cards
     * @return The count of cards by type and rarity, or 0 if the Pokedex is empty.
     */
    public int countByTypeAndRarity(Type type, Rarity rarity, ArrayList<Card> pokedex) {

        if (pokedex.isEmpty()) {
            return 0;
        }

        int count = 0;

        for (Card card : pokedex) {

            if (card.getType().equals(type) && card.getRarity().equals(rarity)) {
                count++;
            }

        }

        return count;

    }

    /**
     * Description: Converts a 2D String matrix into a formatted String ready for
     * console printing.
     * 
     * @param matrix The 2D String matrix to be converted.
     * @return A formatted String representation of the matrix.
     */
    public String matrixToString(String[][] matrix) {
        if (matrix == null || matrix.length == 0) {
            return "Matrix is empty or null.";
        }

        int rows = matrix.length;
        int cols = matrix[0].length;

        // Step 1: Calculate the maximum width of each column
        int[] maxColWidths = new int[cols];
        for (int col = 0; col < cols; col++) {
            for (int row = 0; row < rows; row++) {
                if (matrix[row][col] != null) {
                    maxColWidths[col] = Math.max(maxColWidths[col], matrix[row][col].length());
                }
            }
        }

        // Step 2: Build the formatted string
        StringBuilder result = new StringBuilder();
        for (String[] row : matrix) {
            for (int col = 0; col < cols; col++) {
                String cell = row[col] != null ? row[col] : "";
                result.append(String.format("%-" + maxColWidths[col] + "s", cell)).append(" "); // Left-align each cell
            }
            result.append("\n"); // Add a new line after each row
        }

        return result.toString();
    }

    /**
     * Description: Generates a matrix representation of the Pokedex grouped by
     * Pokémon type.
     * Each row in the matrix corresponds to a specific Pokémon type, and the
     * columns contain the names of the cards belonging to that type.
     * 
     * Precondition: The pokedex ArrayList must be initialized and may contain Card
     * objects.
     * 
     * @param pokedex The ArrayList of Card objects representing the Pokedex.
     * @return A 2D String matrix where rows represent Pokémon types and columns
     *         contain card names.
     */
    public String generateMatrixByType(ArrayList<Card> pokedex) {

        String[][] pokedexMatrixByType = new String[countMostFrequentType(pokedex) + 1][calculateUniquePokemonTypes()];
        ArrayList<Card> clone = new ArrayList<Card>();
        clone.addAll(pokedex);

        if (pokedex.isEmpty()) {
            return null;
        }

        for (int i = 0; i < pokedexMatrixByType.length; i++) {
            for (int j = 0; j < pokedexMatrixByType[i].length; j++) {

                if (i == 0) {
                    pokedexMatrixByType[i][j] = Type.values()[j].toString();

                } else {

                    if (!clone.isEmpty()) {
                        for (Card card : clone) {

                            if (card.getType().toString().equals(pokedexMatrixByType[0][j])) {
                                pokedexMatrixByType[i][j] = card.getId() + "";
                                clone.remove(card);
                                break;

                            }

                        }
                    }
                }

            }

        }

        return matrixToString(pokedexMatrixByType);

    }

    /**
     * Description: Generates a matrix representation of the Pokedex grouped by
     * Pokémon type and rarity.
     * Each row in the matrix corresponds to a specific Pokémon type, and the
     * columns contain the names of the cards grouped by their rarity within that type.
     * 
     * Precondition: The pokedex ArrayList must be initialized and may contain Card
     * objects.
     * 
     * @param pokedex The ArrayList of Card objects representing the Pokedex.
     * @return A 2D String matrix where rows represent Pokémon types and columns are
     *         grouped by rarity.
     */
    public String generateMatrixByTypeAndRarity(ArrayList<Card> pokedex) {

        String[][] pokedexMatrixByTypeAndRarity = new String[countMostFrequentType(pokedex)
                + 1][calculateUniquePokemonTypes()
                        + 1];
        ArrayList<Card> clone = new ArrayList<Card>();
        clone.addAll(pokedex);

        if (pokedex.isEmpty()) {
            return null;
        }

        for (int i = 0; i < pokedexMatrixByTypeAndRarity.length; i++) {
            for (int j = 0; j < pokedexMatrixByTypeAndRarity[i].length; j++) {

                if (i == 0 && j != 0) {
                    pokedexMatrixByTypeAndRarity[i][j] = Type.values()[j - 1].toString();

                } else if (j == 0 && i != 0) {
                    pokedexMatrixByTypeAndRarity[i][j] = Rarity.values()[i - 1].toString();

                } else {

                    if (!clone.isEmpty()) {
                        for (Card card : clone) {

                            if (card.getType().toString().equals(pokedexMatrixByTypeAndRarity[0][j]) &&
                                    card.getRarity().toString().equals(pokedexMatrixByTypeAndRarity[i][0])) {
                                pokedexMatrixByTypeAndRarity[i][j] = countByTypeAndRarity(Type.values()[j - 1],
                                        Rarity.values()[i - 1], pokedex) + "";
                                clone.remove(card);
                                break;

                            }

                        }
                    }
                }

            }

        }

        return matrixToString(pokedexMatrixByTypeAndRarity);

    }

}
